### ISSUE TITLE
The closedbeta user engagement plan

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/dcp#146]
This ticket aims to collect all the tasks needed to establish and operate the closed beta from a user engagement perspective.

The draft plan is described in google docs. This has been passed to the GG for comment on 3rd October
I am going to propose we go with the alternative recruitment strategy as described in 

https://docs.google.com/document/d/1cyv_gMj8FihCj9bcvyyFne9XiD45SKH62FxHFK96vqg/edit?usp=sharing

This involves tier 1 recruitment from the pilot dataset tests and a broader recruitment for tier 2.

Someone probably needs to turn these epics into a better list of tasks but this is what I am aware of

- [x] Take on feedback from GG (if any arrives)
- [x] Write recruitment form
- [x] Collect tier 1 recruitment email list
- [x] Establish tier 2 recruitment lists
- [x] Define briefing process for testers for beginning of Tier 1 
- [x] Write briefing documents Tier 1
- [x] Establish feedback collection routes
- [x] Work out if external support is needed to run the second phase of the beta test
- [x] Recruit external support if needed
- [x] Define briefing process for testers for beginning of Tier 2 
- [ ] Write briefing documents Tier 2
- [ ] Plan the beta test hackathon at CZI on ~4th/5th~ with Jonah and Arne - **postponed**

**Comment by lauraclarke** [comment]
@jonahcool @gabsie @adriennes @kozbo @TimothyTickle @briandoconnor @theathorn 

I have created this as a placeholder for tracking the planning for the user engagement aspect of the closed beta

**Comment by kozbo** [comment]
Also, here is the detailed planning document:
https://docs.google.com/document/d/1O2Fph4NxvoufGJi2FYEp7OlPlQYdiLfXCHvdLf7gFwA/edit

**Comment by kozbo** [comment]
closing this as we will need to create a new epic now that the tasks moved to dcp-community
