### ISSUE TITLE
Components provide a “health check” HTTPS endpoint

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/dcp#281]
Each component must provide a `/health` HTTPS endpoint that should, at the very minimum respond with status 200 if the service is up and healthy.  A response body may be present that provides additional information, that if present must be a JSON object.

- [x] Metadata /health point returns 200
- [x] Ingest /health point returns 200
- [x] Upload /health point returns 200
- [x] DSS /health point returns 200
- [x] Pipelines /health point returns 200
- [x] Matrix /health point returns 200
- [ ] Azul /health point returns 200
- [x] Browser /health point returns 200
- [x] Portal /health point returns 200
- [x] Logging /health point returns 200
- [x] Metrics /health point returns 200

**Comment by brianraymor** [comment]
@rhiananthony, @stahiri , @sampierson - I'm confused why this dcp DevSecOps epic was closed without comment when there are live component issues assigned to this epic. Can you advise?

**Comment by stahiri** [comment]
+ Hannes for Data Browser/Portal/Azul
+ Zina for Metadata

**Comment by brianraymor** [comment]
@stahiri - not sure why this in *In Progress* in *General Availability*. Can the release be cleared and this issue sent to the Icebox?

**Comment by parthshahva** [comment]
Can't this ticket be closed? Pretty sure all components have health checks now

**Comment by stahiri** [comment]
Confirm that ingest has a health endpoint. Closing.
