### ISSUE TITLE
Support 10xV2 data with modular cloud best practices pipeline

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#284]
- [x] Implement Optimus pipeline
- [x] Release to production
- [x] Reanalyze datasets in production
- [x] Gene expression matrices created by Optimus are accessible via the matrix service and data browser
- [x] Users can choose whether they want the analysis results from previous pipeline (Cellranger) or Optimus via data portal, matrix service, and CLI.

**Comment by kbergin** [comment]
I've removed myself from the assignee list as the pipeline has been updated in integration and validated by downstream services. It will make it up into production through the release process.

**Comment by brianraymor** [comment]
Latest update seems to be - https://humancellatlas.slack.com/archives/CJS5DJEEA/p1561558999019200?thread_ts=1561465165.013700&cid=CJS5DJEEA

**Comment by brianraymor** [comment]
@kylee and @jkaneria - should https://github.com/humancellatlas/secondary-analysis/issues/548 be added to this epic instead of being in https://github.com/HumanCellAtlas/secondary-analysis/issues/486 ?

**Comment by kbergin** [comment]
@brianraymor No. This is a ticket of the secondary analysis epic in 486. But I have added 486 as an epic within this ticket.

**Comment by brianraymor** [comment]
RE Optimus data and the matrix service - the [Add UMI count filter to optimus ETL](https://github.com/HumanCellAtlas/matrix-service/pull/354) PR was approved today and addresses the [*hey question about loading the optimus data into the matrix service*](https://humancellatlas.slack.com/archives/C6C5S6B5W/p1564076065012100) thread in data-pipelines team slack. @mckinsel expects to merge it tomorrow (August 1) morning.

**Comment by brianraymor** [comment]
Hi @kylee and @jkaneria - what constitutes "done" for https://github.com/HumanCellAtlas/secondary-analysis/issues/486 from your perspective? For example, all currently available 10X datasets processed?
