### ISSUE TITLE
A dashboard of metrics is available for ops to monitor the aggregate activity of each component

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/dcp#285]
As a DCP component ops person,
I want to see a dashboard of metrics for my component,
so I can tell how my component has performed recently, and tell if it:
- seems unhealthy
- is being unintentionally misused
- is under malicious attack

Dashboards should include, among other key metrics, HTTP error rates for API endpoints.
It is also wise to graph API response latencies.

- [ ] Ingest
- [x] Upload
- [x] Data Store
- [x] Analysis
- [x] Matrix
- [x] Azul
- [x] Portal
- [x] Logs

**Comment by sampierson** [comment]
Copying in useful info from ticket #66:

We want to know how often our API endpoints are not working properly. 

At a minimum we should have logs (hopefully metrics too) for the top-level HTTP services in each box that show the following
- HTTP status classes (2xx, 3xx, 4xx, 5xx) for the box's major APIs**

Optionally
- HTTP status codes broken down into dimensions of endpoint and HTTP method

If the system interface is not HTTP, analogous metrics that indicate the following should be used.
- System wide success and failure
- Request status by system function

The information for these metrics
- MUST be logged
- MAY be sent to CloudWatch Metrics (for easier dashboarding)
- SHOULD be configured in a dashboard for your system, preferably in grafana (either by ES or CloudWatch Metric query)

**Log metrics example here
https://github.com/HumanCellAtlas/health-check/blob/master/dss.tf#L34-L80

![image.png](https://images.zenhubusercontent.com/5a9f2a304b5806bc2bc9b485/99eb35f2-220c-4af9-a9b7-9b03bebc76ab)

- [ ] HTTP Status Classes for ingest
- [x] HTTP Status Classes for data store
- [x] HTTP Status Classes for upload
- [ ] HTTP Status Classes for Data portal
- [x] HTTP Status Classes for secondary analysis

**Comment by justincc** [comment]
Are these the dashboards in Grafana?

**Comment by sampierson** [comment]
Grafana is one possible implementation (that most DCP components have used), but the requirement doesn't care how you do it.

**Comment by stahiri** [comment]
@justincc Could you provide a status update on this one for ingest? Do you expect this work to be completed in Q3?

@NoopDog - could you also please provide a status update on this one for portal? Do you expect this work to be completed in Q3?

**Comment by justincc** [comment]
Ingest now has a [dashboard](https://metrics.dev.data.humancellatlas.org/d/dLLhy0qik/ingest?orgId=1) but it is a work-in-progress. I anticipate more work happening on it in Q3 but likely will not complete.

**Comment by brianraymor** [comment]
@stahiri and @justincc and @kozbo  - can you advise on the state of this issue and its actual owner (thinking that's not Justin). It's not a Q2 or Q3 roadmap objective which are the priorities. It's _In Progress_ without a Release or Milestone. There is one _In Progress_ child issue in the data store. But then there are the outdated checkbox style lists in the top-level summary comment with Ingest and Portal unchecked. Bit of a curate's egg.

**Comment by justincc** [comment]
I'm not sure why I was set as the owner. Status is still the same, we have a dashboard but it's a wip. I am not anticipating completion before the end of Q3.

**Comment by kozbo** [comment]
Data Store is complete on this, and we have been extending our monitoring.
It sounds like we should check to see if the Portal has a dashboard. If so then we can close this. @theathorn

**Comment by theathorn** [comment]
@NoopDog @achave11 Does https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/humancellatlas.github.io/5 imply that the Portal and Browser have Grafana dashboards?

**Comment by achave11** [comment]
@theathorn That is correct. We have the Browser and Portal together in Grafana [dashboard](https://metrics.dev.data.humancellatlas.org/d/data-portal-dev/data-browser-and-portal-dev?orgId=1).
