### ISSUE TITLE
DCP Support for SS2 Flavors

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#344]
SE, PE, Fluidigm, and plate-based

Why? Small variations in the SS2 pipeline enables it to process more data types.

Q3 Scope
- [ ] SE SS2 can run in the DCP

Q2 Scope
- [x] Smartseq2 pipeline can process Single End SS2 data
- [x] Test data is created for these pipelines

Already done
Metadata support
Portal support

**Comment by kbergin** [comment]
Duplicate issue.
