### ISSUE TITLE
Data consumers can search for data of interest to find a sample with specific constraints

### ISSUE THREAD

**Issue by tjchen** [HumanCellAtlas/dcp#361]
## Assumptions and Background

Users of the DCP need to be able to search and find data of the following types from the DCP:
1. Primary data and metadata, before the DCP pipelines have been run
2. Secondary data output and metadata, the output of one or more DCP pipelines
3. Consolidated cell x gene data and metadata

Although there are different ways for data consumers to find data in the DCP, the scope of this epic is limited to cover the feature set initially supporting the Internal DCP developer and Internal APIs, although it is expected that over time the analysis roadbuilder will be a critical user of this system.

### Proposed scope for 2019Q2
Scope of this Epic covers:
1. Validating that a core set of fields are searchable (this would be by matrix service, or the portal)
2. Validate that usability of query service (e.g. SQL) is easier than the current elasticsearch
3. Enumerate the critical search use cases that will be valuable to querying metadata and secondary metadata directly

### Carryover from 2019Q2 to 2019Q3
This epic has taken longer than expected. The diary portion of the UX study and more tightly defining user stories is carried over into 2019Q3.

Root causes:
1. At first, the team was misaligned on the goals of the UX study
2. A PR with missing tests broke the ETL, delaying the diary study
3. Waiting for responses from the diary study has taken longer than expected

Learnings/remediations:
1. Synched on UX study and started working on a small, focused set of questions
2. Repaired tests, will work towards smaller, complete PRs

### Status EO2019Q3
The [UX study](https://docs.google.com/presentation/d/1BZFZ4qxPbOLnqegEklG6i-KRRfaN4-jJ6MQB6y9N1Uc/edit#slide=id.g646c41f790_0_304) has been completed. High-level findings:
* The Query Service was found to be above DSS ES UX baseline, but still not accessible enough to outside developers
* Some queries are possible in QS that are not possible with DSS's ES cluster
* Improvements in error reporting, the query IDE, and bug fixes are necessary to push the product forward
* @GenevieveHaliburton has done a separate study (using the Matrix Service) on what fields users desire from our APIs and found that we are missing critical fields

**Comment by brianraymor** [comment]
@mweiden - please update with a ZenHub milestone.

**Comment by kislyuk** [comment]
(from @GenevieveHaliburton)

To ship the [diary study](https://docs.google.com/document/d/1a_Es4uKuZZa-u_vPn6R357uWpc2zCGpa_klMILfnSos), we need:
- [ ] up to date documentation
- [ ] all of the links in the diary study work
- [ ] the test queries in the diary study can be constructed
- [ ] the test queries in the diary study consistently yield the same results
- [ ] there is a stable set of studies and metadata for a two week period that the participants can use to perform the diary study
goal: ship this end of the week, but let's discuss if there are other additional blockers

**Comment by kislyuk** [comment]
Blocked by https://github.com/HumanCellAtlas/query-service/issues/243

**Comment by GenevieveHaliburton** [comment]
Findings from UX study (interviews and diary study): https://docs.google.com/presentation/d/1BZFZ4qxPbOLnqegEklG6i-KRRfaN4-jJ6MQB6y9N1Uc/edit?usp=sharing

**Comment by mweiden** [comment]
The proposed scope for this epic has been completed.
