### ISSUE TITLE
Cut maximum time wranglers must wait to complete submissions due to metadata schema incompatibility ...

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/dcp#419]
## September 25 Update - change in Release and Milestone: This objective will slip into Q4M1.

The reason for the slip is due to my not allocating enough slack to accommodate time for other work activities. I got distracted and didn't prioritize the completion of this ticket enough and furthermore forgot that September 20th was the end of the quarter. There are two tickets left that should easily be finished by M1 of Q4. Even with additional "slack/Slack" time :)

## Need / User Story

* As a data wrangler working on the DCP
* I want to make adapt the DCP metadata schema quickly
* in order to respond to developments in experimental approaches and new assays.

For more see the [Problem Statement section](https://docs.google.com/document/d/18C_Wbrr4Huc8yxQXSdNbzeGk0glBjkfq0MGnozwlIB8/edit#bookmark=id.xalodf8m8x9j) of @maniarathi's Metadata Integration Testing Design doc.

## Definition of Done

- [ ] implement a [metadata schema integration test](https://docs.google.com/document/d/18C_Wbrr4Huc8yxQXSdNbzeGk0glBjkfq0MGnozwlIB8/edit) that accelerates the promotion of metadata schema changes
- [ ] start measuring lead/turnaround time on data submissions
- [ ] Make necessary changes to the data wrangling SOP

**Comment by brianraymor** [comment]
@mweiden - how do #372 and #373 relate to this epic?

**Comment by diekhans** [comment]
It would be good if measuring includes details of where the time went.

**Comment by mweiden** [comment]
@brianraymor linked #372 and #373

**Comment by maniarathi** [comment]
September 25 Update - change in Release and Milestone: This objective will slip into Q4M1. 

The reason for the slip is due to my not allocating enough slack to accommodate time for other work activities. I got distracted and didn't prioritize the completion of this ticket enough and furthermore forgot that September 20th was the end of the quarter. There are two tickets left that should easily be finished by M1 of Q4. Even with additional "slack/Slack" time :)
