### ISSUE TITLE
Update existing subscriptions to only receive data adhering to compatible schemas

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/dcp#437]
For each downstream component that has a subscription registered with the DSS to receive data, determine what current versions of metadata schemas they are compatible with and specify the range in the subscriptions. Only ranges that are not "all" will need to be specified. 

Tasks:
- [ ] Update Matrix Service subscription
- [ ] Update Query Service subscription
- [ ] Update Data Browser subscription
- [ ] Update Secondary Analysis subscription

**Comment by maniarathi** [comment]
Closing as this was incorrectly created.
