### ISSUE TITLE
Method to delineate community-pipeline analyzed data vs HCA-approved pipeline analyzed data

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#56]
There is a desire to have as many at-least-community-approved "v1" pipelines running in the DCP to enable as much science as possible. We will have continued efforts to create HCA AWG pipeline subgroup approved pipelines that are of what we determine to be the highest quality. We will require a way to delineate these two types of pipelines and output data in the HCA (via metadata) and via the access portal, documentation, and maybe even the CLI so that it is very clear to users.

AC:
- [ ] AWG subgroup approves designs for delineation
- [ ] Spike on design for implementation across DCP
- [ ] Implementation of the design
