### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#63]
As the DCP Operations team we need clear and helpful logs for troubleshooting, monitoring, and notifications.  Parth will be a great champion for this.

- [x] Setting logging standards for operations dashboard
- [x] blue linked to centralized logging
- [x] green linked to centralized logging
- [x] ingest linked to centralized logging
- [x] staging linked to centralized logging
- [x] deploy to production environment
- [x] integration linked to centralized logging
- [x] green box prod linked to centralized logging
- [x] orange box linked to centralized logging

**Comment by kbergin** [comment]
Dev account for AWS which has dev, int, staging and those are all linked to the logging. Dev ELK and Dev Grafana for logs. Prod account for AWS also has ELK and Grafana. Green box needs to manually submit for the Google side.

**Comment by kbergin** [comment]
I believe because we do not use AWS we have to do something different to be able to submit logs for Green. @rhiananthony , @rexwangcc or @mweiden should be better able to answer.

**Comment by mweiden** [comment]
Right. It's the same process that we did before for your dev deployments. You create log "sinks" to a pubsub topic and then send me the service account emails that will be publishing to those topics. That's all! DM me for details.

**Comment by brianraymor** [comment]
Is this redundant with the new logging epics - https://github.com/HumanCellAtlas/dcp/issues?utf8=%E2%9C%93&q=logs ?
