### ISSUE TITLE
API Error Metrics

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#66]
We want to know how often our API endpoints are not working properly. 

At a minimum we should have logs (hopefully metrics too) for the top-level HTTP services in each box that show the following
- HTTP status classes (2xx, 3xx, 4xx, 5xx) for the box's major APIs**

Optionally
- HTTP status codes broken down into dimensions of endpoint and HTTP method

If the system interface is not HTTP, analogous metrics that indicate the following should be used.
- System wide success and failure
- Request status by system function

The information for these metrics
- MUST be logged
- MAY be sent to CloudWatch Metrics (for easier dashboarding)
- SHOULD be configured in a dashboard for your system, preferably in grafana (either by ES or CloudWatch Metric query)

**Log metrics example here
https://github.com/HumanCellAtlas/health-check/blob/master/dss.tf#L34-L80

![image.png](https://images.zenhubusercontent.com/5a9f2a304b5806bc2bc9b485/99eb35f2-220c-4af9-a9b7-9b03bebc76ab)

- [ ] HTTP Status Classes for ingest
- [x] HTTP Status Classes for data store
- [x] HTTP Status Classes for upload
- [ ] HTTP Status Classes for Data portal
- [x] HTTP Status Classes for secondary analysis

**Comment by sampierson** [comment]
This functionality is a subset of ticket #285.  I have copied this info there and am closing this one.
